sudo: false
language: node_js
node_js:
  - "8"
before_install:
  - npm install -g codecov
script:
  - npm run test:bs
  - npm run remap-istanbul
after_success:
  - codecov
after_failure:
  - codecov
env:
  global:
    - secure: EnyvoGt80dDpoZ901HVq6zlFMGd0UT7ehsbCBoBvZw1A685CpaSbiMPkvtYOMWbv1JtUhncGwUIbXwYUE0V38ShtNy3xl73i/egqby5YCVlmt27Jb1Zgv/qYXgnJKGdwhPkczK3p27MXHDj5KmSeseEy5qBU8ef45UMzCmIyyCtG3GiNtfzXHJzI0MDCpHwaeYScqN/UyDGPeOtIhacAClojD2G24ZbQvBZ7uriL7t5ZrDy2h18S2EHEa/QMJC8o4KxX9JkN7bFkV3R50E6kI7Y/UM1/FtP6znJt8ICk+5nymeaUyd/LF/CzWVGnVAI9+eKCvDIKs3IuCo9Fqwe5qUXtYhOdySeK5hQlvg9cQXsBthF8qCzyIo+6TdkUscH2HfXV4fACYS1haCZVWiw+K8Wnw7Bfjo4bhWMf1MjgflHX0hsVia89AOXgnxd31BISnd8O2z3qchoGcuBNhJHN0ySRIS9FnU0OThMWG9KfWpzY5LcyemwGGuyB4iTik4FGq4qpRUev7jY2i88ICdojOxYDIRfra891QNlARTXyYi0vlGyWlzg65UUhUHp0cszF+VDhYpelOvvn9JbbqP3Z4KnVTpudsnV3FUQ0/qcbAtNOpDpgmW9d3FeDTXHW0dfM3nDIIdE1NNHGjsONd8XMlQ4cvE2Liwk4tzS6VpuScMk=
    - secure: ocVm0yv2WTR/EiD3r8t44RR+0/kSDyGjzD5//ePGlsXOVmXAlPEKUfy2cYEmjgRBopbCum2ICAYyFqVjNlip1imjVzHnlgf57bID7AWzbbqeRYF8CUL/t+yh0/MpPGOwDOTDgj7y6EVh2cDgXu5zCJICO+wlqQDJUP3Vdi91yHAFEsppMZb+zinnWgFoLcMQqOoq1gesJU1iFa9ZdLO86656xbS9Nv0gcxYTrlQFnhjHou9zggdg1QrFTHoBAkfLI6GD5sWj5bB6kQROyiUC35QvKqCumQLV2HQIWYTxuZqw0kUBj22QhuG7vs+Aiizlaaa+1h8hU5OpdagZ9rGjxc5WWKdw5Frxu2fjqopQPSr9EscMEHlKf7BZpMJsZ6o7YXM03YRU7HUoVUPsYeSHQTTUHWIPQwAoFxEdq5mRXCPfZSux0AhDZ9Ixgmdb0j7IMzIo+82Nk5nUKeQEKo4EVuCdzfy7sdF1j8Vcz2RKt/s9yOKO4Q17M/cr2VECtuvnyInxS5NxsqIzDPc5cqRDHuiDKR92Aeo+JNEGt6a595zqSSFKGwQ0ijm6ASdxi6R91sg27DClE43Ov6HkerlRYZteYjAI4kruMJg07N1NVkjdNoDLSmf8+27h1D3k1zvvNamKrx/b+dLGFyBoTkYIbAvpE4LYkmtndbRpXRia4ls=
